name: Backend CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the backend code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Dockerize the backend
      - name: Build Docker image for backend
        run: |
          docker build -t backend-image:latest .

      # Log in to Docker Hub (or any container registry)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Push Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker tag backend-image:latest hillaarts/backend-image:latest
          docker push hillaarts/backend-image:latest

      # Deploy the app to server using SSH
      - name: Deploy to Server
        run: |
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ubuntu@35.153.33.107 'docker pull hillaaarts/backend-image:latest && docker-compose up -d'
